# 项目的.drone.yml 文件
kind: pipeline
type: docker
name: erp-web

steps:
  # 构建缓存
  - name: loading cache # 加载缓存
    pull: if-not-exists # 如果镜像不存在则拉取,免去每次都要重新下载
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules

  # npm 构建
  - name: npm-build
    pull: if-not-exists
    image: 192.168.6.12:3002/library/node:22.17.1
    commands:
      - pwd
      - ls -alt

      - npm config set registry https://registry.npmmirror.com
      - npm i -g pnpm
      - pnpm store prune
      - pnpm install
      - pnpm build

  # 构建镜像并推送到镜像仓库
  - name: build-docker-image
    pull: if-not-exists
    image: plugins/docker
    settings:
      username: admin
      password:
        from_secret: harbor_admin_password
      registry: 192.168.6.12:3002
      repo: 192.168.6.12:3002/erp-web/web
      debug: true
      insecure: true
      tags:
        - v1.0

      # 开始部署通知
  - name: feishu-notify-test-start
    pull: if-not-exists
    image: plugins/webhook
    settings:
      urls: 'https://open.feishu.cn/open-apis/bot/v2/hook/0855b6bf-0a5c-4a97-8b83-5efd8e84d09d'
      method: 'POST'
      content_type: application/json
      skip_verify: true
      debug: true
      template: |
        {
          "msg_type": "post",
          "content": {
            "post": {
              "zh_cn": {
                "content": [
                  [{
                    "tag": "at",
                    "user_id": "all"
                  },{
                    "tag": "text",
                    "text": "test环境系统部署通知:项目开始部署中.... "
                  }]
                ]
              }
            }
          }
        }
    when:
      branch: local-dev

      # 部署到测试环境
  - name: deploy-run-test
    pull: if-not-exists
    image: appleboy/drone-ssh
    settings:
      host: 192.168.6.14
      port: 22
      username: attom-14
      password:
        from_secret: ssh_password
      # 使用docker compose拉去对应的镜像，并运行
      script:
        - cd ~/app/erp/web && docker compose pull && docker compose up -d
    when:
      branch: local-dev

  # prod 开始通知
  - name: feishu-notify-prod-start
    pull: if-not-exists
    image: plugins/webhook
    settings:
      urls: 'https://open.feishu.cn/open-apis/bot/v2/hook/8abd8f3c-4550-4d44-9729-22e772b80181'
      method: 'POST'
      content_type: application/json
      skip_verify: true
      debug: true
      template: |
        {
          "msg_type": "post",
          "content": {
            "post": {
              "zh_cn": {
                "content": [
                  [{
                    "tag": "at",
                    "user_id": "all"
                  },{
                    "tag": "text",
                    "text": "新系统部署通知:项目开始部署中.... "
                  }]
                ]
              }
            }
          }
        }
    when:
      branch:
        prod

        # 部署到生成环境
  - name: deploy-run-prod
    pull: if-not-exists
    image: appleboy/drone-ssh
    settings:
      host: 192.168.6.12
      port: 22
      username: attom-12
      password:
        from_secret: ssh_password
      # 使用docker compose拉去对应的镜像，并运行
      script:
        - cd ~/app/erp/web && docker compose pull && docker compose up -d
    when:
      branch: prod

  # 构建缓存
  - name: rebuild-cache
    pull: if-not-exists
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules

  # 项目部署结束通知
  - name: feishu-notify-test-end
    pull: if-not-exists
    image: plugins/webhook
    settings:
      urls: 'https://open.feishu.cn/open-apis/bot/v2/hook/0855b6bf-0a5c-4a97-8b83-5efd8e84d09d'
      method: 'POST'
      content_type: application/json
      skip_verify: true
      debug: true
      template: |
        {
          "msg_type": "post",
          "content": {
            "post": {
              "zh_cn": {
                "content": [
                  [{
                    "tag": "at",
                    "user_id": "all"
                  },{
                    "tag": "text",
                    "text": "test环境系统部署通知:项目部署完成 "
                  }]
                ]
              }
            }
          }
        }
    when:
      branch: local-dev

  # prod 结束通知
  - name: feishu-notify-prod-end
    pull: if-not-exists
    image: plugins/webhook
    settings:
      urls: 'https://open.feishu.cn/open-apis/bot/v2/hook/8abd8f3c-4550-4d44-9729-22e772b80181'
      method: 'POST'
      content_type: application/json
      skip_verify: true
      debug: true
      template: |
        {
          "msg_type": "post",
          "content": {
            "post": {
              "zh_cn": {
                "content": [
                  [{
                    "tag": "at",
                    "user_id": "all"
                  },{
                    "tag": "text",
                    "text": "新系统部署通知:系统部署完成 "
                  }]
                ]
              }
            }
          }
        }
    when:
      branch: main

# 挂载卷
volumes:
  - name: cache
    host:
      path: /tmp/drone-cache

# matster分支触发构建
trigger:
  branch:
    - local-dev
    - prod
