# 项目的.drone.yml 文件
kind: pipeline
type: docker
name: web

steps:
  # npm 构建1
  - name: npm-build
    image: 192.168.6.12:3002/library/node:20.15.1
    commands:
      - pwd
      - ls -alt
      - npm config set registry https://registry.npmmirror.com
      - npm i -g pnpm
      - pnpm install --verbose
      - npm run build:fast

  # 打包构建镜像并推送到镜像仓库
  - name: build-docker-image
    image: plugins/docker
    settings:
      username: admin
      password:
        from_secret: harbor_admin_password
      registry: 192.168.6.12:3002
      repo: 192.168.6.12:3002/erp-web/web
      debug: true
      insecure: true
      tags:
        - v1.0
      build_args:
        - --no-cache

  # 远程到主机并运行
  - name: deploy-run
    image: appleboy/drone-ssh
    pull: true
    settings:
      host: 192.168.6.12
      port: 22
      username: attom-12
      password:
        from_secret: ssh_password
      # 使用docker compose拉去对应的镜像，并运行
      script:
        - cd ~/app/project_install && docker compose pull && docker compose up -d

# matster分支触发构建
trigger:
  branch:
    - local-dev
