FROM node:20.15.1

# 设置工作目录
WORKDIR /app

# 复制 package.json 和 package-lock.json
COPY package*.json ./

# 安装依赖
RUN npm install

# 复制项目文件到工作目录
COPY . .

# 构建 Vue 项目
RUN npm run build

# 阶段 2: 运行阶段
FROM nginx:latest

# 删除默认的 Nginx 静态文件
RUN rm -rf /usr/share/nginx/html/*

# 将构建的静态文件复制到 Nginx 的静态目录
COPY --from=build /app/dist /usr/share/nginx/html

# 可选: 添加自定义 Nginx 配置
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# 暴露端口
EXPOSE 80

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]
