# 使用官方 nginx 镜像
FROM nginx:alpine

# 删除默认 Nginx 配置文件
RUN rm -rf /usr/share/nginx/html/*

# 将 Vue 项目构建的静态文件拷贝到 Nginx 的 HTML 目录
COPY dist/ /usr/share/nginx/html/

# 暴露端口
EXPOSE 80

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]
