
export const ROLE_BOSS_CODE = "ROLE_BOSS"

export const ROLE_PURCHASER_CODE = "ROLE_PURCHASER" // 采购
export const ROLE_PURCHASINGASSISTANT_CODE = "ROLE_PURCHASINGASSISTANT" // 采购助理


export const ROLE_GRAPHICDESIGNLEAD_CODE = "ROLE_GRAPHICDESIGNLEAD" //平面设计主管
export const ROLE_GRAPHICDESIGNER_CODE = "ROLE_GRAPHICDESIGNER" // 平面设计
export const ROLE_INDUSTRIAL_DESIGN_CODE = "ROLE_INDUSTRIAL_DESIGN" // 工业设计

export const ROLE_LOGISTISCSPECIALIST_CODE = "ROLE_LOGISTISCSPECIALIST" // 物流管理

export const ROLE_PRODUCTMANNAGERLEAD_CODE = "ROLE_PRODUCTMANNAGERLEAD" // 产品经理主管
export const ROLE_PRODUCTMANAGER_CODE = "ROLE_PRODUCTMANAGER" // 产品经理
export const ROLE_ADMINBUYERLEAD_CODE = "ROLE_ADMINBUYERLEAD" // 行政主管

export const ROLE_SUPPLY_CHAIN_MANG_CODE = "ROLE_SUPPLY_CHAIN_MANG" // 供应链管理



