/**
 * @description 4个子配置，cli配置|通用配置|主题配置|网络配置导出
 */
import { cliConfig } from '/@/config/cli.config'
import { netConfig } from '/@/config/net.config'
import { settingConfig } from '/@/config/setting.config'
import { themeConfig } from '/@/config/theme.config'

const config: { [key: string]: any } = {
  ...cliConfig,
  ...netConfig,
  ...settingConfig,
  ...themeConfig,
}

export default config

export const {
  uniqueOpened,
  tokenTableName,
  tokenName,
  titleSeparator,
  titleReverse,
  title,
  timeout,
  themeName,
  tabsBarStyle,
  supportVisit,
  successCode,
  storage,
  statusName,
  showThemeSetting,
  showTheme,
  showTabsIcon,
  showTabs,
  showSearch,
  showRefresh,
  showProgressBar,
  showNotice,
  showLock,
  showLanguage,
  showFullScreen,
  showFooter,
  showDark,
  showColorPicker,
  routesWhiteList,
  rolesControl,
  reportCompressedSize,
  report,
  recordRoute,
  radius,
  pwa,
  prodEnabled,
  port,
  pageTransition,
  outputHash,
  outDir,
  openFirstMenu,
  open,
  noDebugger,
  minify,
  messageName,
  messageDuration,
  menuWidth,
  logo,
  loginRSA,
  loginInterception,
  localEnabled,
  loadingText,
  layout,
  keepAliveMaxNum,
  isHashRouterMode,
  isFollow,
  isCatchedTabs,
  include,
  i18n,
  https,
  foldSidebar,
  fixedHeader,
  exclude,
  errorLog,
  defaultOpeneds,
  debounce,
  cssCodeSplit,
  copyright,
  contentType,
  compress,
  columnStyle,
  colorWeakness,
  color,
  chunkSizeWarningLimit,
  base,
  authentication,
  assetsDir,
  abbreviation,
} = config
